// The glyphs the glyph editor's picker offers, in groups. Emoji groups hold
// only emoji that terminals draw two cells wide by default, and the other groups
// only one-cell glyphs, so each group's grid lines up. Names come from Unicode
// and, for Nerd Font icons, from the Nerd Fonts glyph names (nf-...). The Nerd
// Font groups draw as boxes without a Nerd Font.
export interface GlyphEntry {
    glyph: string;
    name: string;
    /** An emoji that takes a skin tone: its light tone version, which the other tones are made from. */
    lightTone?: string;
}

export interface GlyphGroup {
    name: string;
    needsNerdFont: boolean;
    glyphs: GlyphEntry[];
}

export const GLYPH_GROUPS: GlyphGroup[] = [
    {
        name: 'Folders & files',
        needsNerdFont: false,
        glyphs: [
            { glyph: '📁', name: 'file folder' },
            { glyph: '📂', name: 'open file folder' },
            { glyph: '📄', name: 'page facing up' },
            { glyph: '📃', name: 'page with curl' },
            { glyph: '📑', name: 'bookmark tabs' },
            { glyph: '📋', name: 'clipboard' },
            { glyph: '📝', name: 'memo' },
            { glyph: '💾', name: 'floppy disk' },
            { glyph: '💿', name: 'optical disc' },
            { glyph: '📀', name: 'dvd' },
            { glyph: '📦', name: 'package' },
            { glyph: '📚', name: 'books' },
            { glyph: '📒', name: 'ledger' },
            { glyph: '📓', name: 'notebook' },
            { glyph: '📔', name: 'notebook with decorative cover' },
            { glyph: '📕', name: 'closed book' },
            { glyph: '📗', name: 'green book' },
            { glyph: '📘', name: 'blue book' },
            { glyph: '📙', name: 'orange book' },
            { glyph: '🔖', name: 'bookmark' },
            { glyph: '📎', name: 'paperclip' },
            { glyph: '📌', name: 'pushpin' },
            { glyph: '📍', name: 'round pushpin' },
            { glyph: '📰', name: 'newspaper' },
            { glyph: '📜', name: 'scroll' },
            { glyph: '📊', name: 'bar chart' },
            { glyph: '📈', name: 'chart with upwards trend' },
            { glyph: '📉', name: 'chart with downwards trend' },
            { glyph: '🧾', name: 'receipt' },
            { glyph: '📇', name: 'card index' },
            { glyph: '🏠', name: 'house building' },
            { glyph: '🏡', name: 'house with garden' },
            { glyph: '🏢', name: 'office building' },
            { glyph: '🧳', name: 'luggage' }
        ]
    },
    {
        name: 'Dev & tools',
        needsNerdFont: false,
        glyphs: [
            { glyph: '💻', name: 'personal computer' },
            { glyph: '🤖', name: 'robot face' },
            { glyph: '👾', name: 'alien monster' },
            { glyph: '🐛', name: 'bug' },
            { glyph: '🐞', name: 'lady beetle' },
            { glyph: '🦠', name: 'microbe' },
            { glyph: '🚀', name: 'rocket' },
            { glyph: '🛸', name: 'flying saucer' },
            { glyph: '🔧', name: 'wrench' },
            { glyph: '🔨', name: 'hammer' },
            { glyph: '🪛', name: 'screwdriver' },
            { glyph: '🪚', name: 'carpentry saw' },
            { glyph: '🧰', name: 'toolbox' },
            { glyph: '🧪', name: 'test tube' },
            { glyph: '🧫', name: 'petri dish' },
            { glyph: '🧬', name: 'dna double helix' },
            { glyph: '🔬', name: 'microscope' },
            { glyph: '🔭', name: 'telescope' },
            { glyph: '📡', name: 'satellite antenna' },
            { glyph: '🔌', name: 'electric plug' },
            { glyph: '🔋', name: 'battery' },
            { glyph: '🪫', name: 'low battery' },
            { glyph: '💡', name: 'electric light bulb' },
            { glyph: '🔦', name: 'electric torch' },
            { glyph: '🧩', name: 'jigsaw puzzle piece' },
            { glyph: '🧮', name: 'abacus' },
            { glyph: '🧲', name: 'magnet' },
            { glyph: '💽', name: 'minidisc' },
            { glyph: '📟', name: 'pager' },
            { glyph: '📠', name: 'fax machine' },
            { glyph: '⌚', name: 'watch' },
            { glyph: '📱', name: 'mobile phone' },
            { glyph: '📲', name: 'mobile phone with rightwards arrow at left' },
            { glyph: '📞', name: 'telephone receiver' },
            { glyph: '🔗', name: 'link symbol' },
            { glyph: '🪝', name: 'hook' },
            { glyph: '🧯', name: 'fire extinguisher' }
        ]
    },
    {
        name: 'Git & status',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🌿', name: 'herb' },
            { glyph: '🌱', name: 'seedling' },
            { glyph: '🔀', name: 'twisted rightwards arrows' },
            { glyph: '🔁', name: 'clockwise rightwards and leftwards open circle arrows' },
            { glyph: '🔂', name: 'clockwise rightwards and leftwards open circle arrows with circled one overlay' },
            { glyph: '🔃', name: 'clockwise downwards and upwards open circle arrows' },
            { glyph: '🔄', name: 'anticlockwise downwards and upwards open circle arrows' },
            { glyph: '🏁', name: 'chequered flag' },
            { glyph: '🚩', name: 'triangular flag on post' },
            { glyph: '🎯', name: 'direct hit' },
            { glyph: '✅', name: 'white heavy check mark' },
            { glyph: '❎', name: 'negative squared cross mark' },
            { glyph: '❌', name: 'cross mark' },
            { glyph: '⭕', name: 'heavy large circle' },
            { glyph: '🚫', name: 'no entry sign' },
            { glyph: '⛔', name: 'no entry' },
            { glyph: '🚧', name: 'construction sign' },
            { glyph: '🔒', name: 'lock' },
            { glyph: '🔓', name: 'open lock' },
            { glyph: '🔐', name: 'closed lock with key' },
            { glyph: '🔏', name: 'lock with ink pen' },
            { glyph: '🔑', name: 'key' },
            { glyph: '🆕', name: 'squared new' },
            { glyph: '🆗', name: 'squared ok' },
            { glyph: '🆙', name: 'squared up with exclamation mark' },
            { glyph: '🆒', name: 'squared cool' },
            { glyph: '🔥', name: 'fire' },
            { glyph: '✨', name: 'sparkles' },
            { glyph: '💥', name: 'collision symbol' },
            { glyph: '🎉', name: 'party popper' },
            { glyph: '🎊', name: 'confetti ball' },
            { glyph: '🏆', name: 'trophy' },
            { glyph: '🥇', name: 'first place medal' },
            { glyph: '🔔', name: 'bell' },
            { glyph: '🔕', name: 'bell with cancellation stroke' },
            { glyph: '💯', name: 'hundred points symbol' },
            { glyph: '⏫', name: 'black up-pointing double triangle' },
            { glyph: '⏬', name: 'black down-pointing double triangle' },
            { glyph: '🔼', name: 'up-pointing small red triangle' },
            { glyph: '🔽', name: 'down-pointing small red triangle' },
            { glyph: '⏩', name: 'black right-pointing double triangle' },
            { glyph: '⏪', name: 'black left-pointing double triangle' },
            { glyph: '🟢', name: 'large green circle' },
            { glyph: '🟡', name: 'large yellow circle' },
            { glyph: '🟠', name: 'large orange circle' },
            { glyph: '🔴', name: 'large red circle' },
            { glyph: '🟣', name: 'large purple circle' },
            { glyph: '🔵', name: 'large blue circle' },
            { glyph: '⚪', name: 'medium white circle' },
            { glyph: '⚫', name: 'medium black circle' }
        ]
    },
    {
        name: 'Weather & time',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🌞', name: 'sun with face' },
            { glyph: '🌝', name: 'full moon with face' },
            { glyph: '🌚', name: 'new moon with face' },
            { glyph: '🌙', name: 'crescent moon' },
            { glyph: '🌛', name: 'first quarter moon with face' },
            { glyph: '🌜', name: 'last quarter moon with face' },
            { glyph: '🌕', name: 'full moon symbol' },
            { glyph: '🌖', name: 'waning gibbous moon symbol' },
            { glyph: '🌗', name: 'last quarter moon symbol' },
            { glyph: '🌘', name: 'waning crescent moon symbol' },
            { glyph: '🌑', name: 'new moon symbol' },
            { glyph: '🌒', name: 'waxing crescent moon symbol' },
            { glyph: '🌓', name: 'first quarter moon symbol' },
            { glyph: '🌔', name: 'waxing gibbous moon symbol' },
            { glyph: '⭐', name: 'white medium star' },
            { glyph: '🌟', name: 'glowing star' },
            { glyph: '💫', name: 'dizzy symbol' },
            { glyph: '⛅', name: 'sun behind cloud' },
            { glyph: '🌈', name: 'rainbow' },
            { glyph: '🌊', name: 'water wave' },
            { glyph: '💧', name: 'droplet' },
            { glyph: '💦', name: 'splashing sweat symbol' },
            { glyph: '⚡', name: 'high voltage sign' },
            { glyph: '⛄', name: 'snowman without snow' },
            { glyph: '🌀', name: 'cyclone' },
            { glyph: '☔', name: 'umbrella with rain drops' },
            { glyph: '⏰', name: 'alarm clock' },
            { glyph: '⏳', name: 'hourglass with flowing sand' },
            { glyph: '⌛', name: 'hourglass' },
            { glyph: '🕐', name: 'clock face one oclock' },
            { glyph: '🕒', name: 'clock face three oclock' },
            { glyph: '🕕', name: 'clock face six oclock' },
            { glyph: '🕘', name: 'clock face nine oclock' },
            { glyph: '🕛', name: 'clock face twelve oclock' },
            { glyph: '📅', name: 'calendar' },
            { glyph: '📆', name: 'tear-off calendar' }
        ]
    },
    {
        name: 'Nature & animals',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🌲', name: 'evergreen tree' },
            { glyph: '🌳', name: 'deciduous tree' },
            { glyph: '🌴', name: 'palm tree' },
            { glyph: '🌵', name: 'cactus' },
            { glyph: '🍀', name: 'four leaf clover' },
            { glyph: '🍁', name: 'maple leaf' },
            { glyph: '🍂', name: 'fallen leaf' },
            { glyph: '🍃', name: 'leaf fluttering in wind' },
            { glyph: '🌸', name: 'cherry blossom' },
            { glyph: '🌺', name: 'hibiscus' },
            { glyph: '🌻', name: 'sunflower' },
            { glyph: '🌼', name: 'blossom' },
            { glyph: '🌷', name: 'tulip' },
            { glyph: '🍄', name: 'mushroom' },
            { glyph: '🐢', name: 'turtle' },
            { glyph: '🐍', name: 'snake' },
            { glyph: '🦀', name: 'crab' },
            { glyph: '🐙', name: 'octopus' },
            { glyph: '🦊', name: 'fox face' },
            { glyph: '🐱', name: 'cat face' },
            { glyph: '🐶', name: 'dog face' },
            { glyph: '🦉', name: 'owl' },
            { glyph: '🐝', name: 'honeybee' },
            { glyph: '🐳', name: 'spouting whale' },
            { glyph: '🦄', name: 'unicorn face' },
            { glyph: '🐧', name: 'penguin' },
            { glyph: '🐘', name: 'elephant' },
            { glyph: '🦖', name: 't-rex' },
            { glyph: '🦕', name: 'sauropod' },
            { glyph: '🐉', name: 'dragon' },
            { glyph: '🐲', name: 'dragon face' },
            { glyph: '🦋', name: 'butterfly' },
            { glyph: '🐌', name: 'snail' },
            { glyph: '🦔', name: 'hedgehog' },
            { glyph: '🦦', name: 'otter' },
            { glyph: '🦥', name: 'sloth' },
            { glyph: '🦭', name: 'seal' },
            { glyph: '🦩', name: 'flamingo' },
            { glyph: '🐺', name: 'wolf face' }
        ]
    },
    {
        name: 'Objects & food',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🎨', name: 'artist palette' },
            { glyph: '🎵', name: 'musical note' },
            { glyph: '🎶', name: 'multiple musical notes' },
            { glyph: '🎧', name: 'headphone' },
            { glyph: '🎮', name: 'video game' },
            { glyph: '🎲', name: 'game die' },
            { glyph: '🎸', name: 'guitar' },
            { glyph: '🎬', name: 'clapper board' },
            { glyph: '📷', name: 'camera' },
            { glyph: '📺', name: 'television' },
            { glyph: '📻', name: 'radio' },
            { glyph: '💬', name: 'speech balloon' },
            { glyph: '💭', name: 'thought balloon' },
            { glyph: '📣', name: 'cheering megaphone' },
            { glyph: '📢', name: 'public address loudspeaker' },
            { glyph: '📬', name: 'open mailbox with raised flag' },
            { glyph: '📮', name: 'postbox' },
            { glyph: '🧭', name: 'compass' },
            { glyph: '🔍', name: 'left-pointing magnifying glass' },
            { glyph: '🔎', name: 'right-pointing magnifying glass' },
            { glyph: '🧹', name: 'broom' },
            { glyph: '🧷', name: 'safety pin' },
            { glyph: '🎁', name: 'wrapped present' },
            { glyph: '🎈', name: 'balloon' },
            { glyph: '🧸', name: 'teddy bear' },
            { glyph: '💎', name: 'gem stone' },
            { glyph: '💰', name: 'money bag' },
            { glyph: '💳', name: 'credit card' },
            { glyph: '🪙', name: 'coin' },
            { glyph: '☕', name: 'hot beverage' },
            { glyph: '🍵', name: 'teacup without handle' },
            { glyph: '🧋', name: 'bubble tea' },
            { glyph: '🍺', name: 'beer mug' },
            { glyph: '🍷', name: 'wine glass' },
            { glyph: '🍕', name: 'slice of pizza' },
            { glyph: '🍔', name: 'hamburger' },
            { glyph: '🌮', name: 'taco' },
            { glyph: '🍩', name: 'doughnut' },
            { glyph: '🍪', name: 'cookie' },
            { glyph: '🍎', name: 'red apple' },
            { glyph: '🍋', name: 'lemon' },
            { glyph: '🍿', name: 'popcorn' }
        ]
    },
    {
        name: 'Faces, hands & hearts',
        needsNerdFont: false,
        glyphs: [
            { glyph: '😀', name: 'grinning face' },
            { glyph: '😄', name: 'smiling face with open mouth and smiling eyes' },
            { glyph: '😎', name: 'smiling face with sunglasses' },
            { glyph: '🤓', name: 'nerd face' },
            { glyph: '🧐', name: 'face with monocle' },
            { glyph: '🤔', name: 'thinking face' },
            { glyph: '😴', name: 'sleeping face' },
            { glyph: '🥳', name: 'face with party horn and party hat' },
            { glyph: '🤯', name: 'shocked face with exploding head' },
            { glyph: '😱', name: 'face screaming in fear' },
            { glyph: '🙃', name: 'upside-down face' },
            { glyph: '😅', name: 'smiling face with open mouth and cold sweat' },
            { glyph: '🥲', name: 'smiling face with tear' },
            { glyph: '😬', name: 'grimacing face' },
            { glyph: '🤖', name: 'robot face' },
            { glyph: '👻', name: 'ghost' },
            { glyph: '💀', name: 'skull' },
            { glyph: '👽', name: 'extraterrestrial alien' },
            { glyph: '👍', name: 'thumbs up sign' },
            { glyph: '👎', name: 'thumbs down sign' },
            { glyph: '👌', name: 'ok hand sign' },
            { glyph: '🤞', name: 'hand with index and middle fingers crossed' },
            { glyph: '👀', name: 'eyes' },
            { glyph: '🙌', name: 'person raising both hands in celebration' },
            { glyph: '👏', name: 'clapping hands sign' },
            { glyph: '💪', name: 'flexed biceps' },
            { glyph: '🧠', name: 'brain' },
            { glyph: '🫡', name: 'saluting face' },
            { glyph: '🫠', name: 'melting face' },
            { glyph: '💙', name: 'blue heart' },
            { glyph: '💚', name: 'green heart' },
            { glyph: '💛', name: 'yellow heart' },
            { glyph: '🧡', name: 'orange heart' },
            { glyph: '💜', name: 'purple heart' },
            { glyph: '🖤', name: 'black heart' },
            { glyph: '🤍', name: 'white heart' },
            { glyph: '🤎', name: 'brown heart' },
            { glyph: '🩷', name: 'pink heart' },
            { glyph: '🩵', name: 'light blue heart' }
        ]
    },
    {
        name: 'Arrows',
        needsNerdFont: false,
        glyphs: [
            { glyph: '←', name: 'leftwards arrow' },
            { glyph: '→', name: 'rightwards arrow' },
            { glyph: '↑', name: 'upwards arrow' },
            { glyph: '↓', name: 'downwards arrow' },
            { glyph: '↔', name: 'left right arrow' },
            { glyph: '↕', name: 'up down arrow' },
            { glyph: '↖', name: 'north west arrow' },
            { glyph: '↗', name: 'north east arrow' },
            { glyph: '↘', name: 'south east arrow' },
            { glyph: '↙', name: 'south west arrow' },
            { glyph: '⇐', name: 'leftwards double arrow' },
            { glyph: '⇒', name: 'rightwards double arrow' },
            { glyph: '⇑', name: 'upwards double arrow' },
            { glyph: '⇓', name: 'downwards double arrow' },
            { glyph: '⇔', name: 'left right double arrow' },
            { glyph: '⇕', name: 'up down double arrow' },
            { glyph: '⇡', name: 'upwards dashed arrow' },
            { glyph: '⇣', name: 'downwards dashed arrow' },
            { glyph: '⇠', name: 'leftwards dashed arrow' },
            { glyph: '⇢', name: 'rightwards dashed arrow' },
            { glyph: '⇄', name: 'rightwards arrow over leftwards arrow' },
            { glyph: '⇅', name: 'upwards arrow leftwards of downwards arrow' },
            { glyph: '⇆', name: 'leftwards arrow over rightwards arrow' },
            { glyph: '↺', name: 'anticlockwise open circle arrow' },
            { glyph: '↻', name: 'clockwise open circle arrow' },
            { glyph: '⟲', name: 'anticlockwise gapped circle arrow' },
            { glyph: '⟳', name: 'clockwise gapped circle arrow' },
            { glyph: '↩', name: 'leftwards arrow with hook' },
            { glyph: '↪', name: 'rightwards arrow with hook' },
            { glyph: '↰', name: 'upwards arrow with tip leftwards' },
            { glyph: '↱', name: 'upwards arrow with tip rightwards' },
            { glyph: '↳', name: 'downwards arrow with tip rightwards' },
            { glyph: '↴', name: 'rightwards arrow with corner downwards' },
            { glyph: '⇥', name: 'rightwards arrow to bar' },
            { glyph: '⇤', name: 'leftwards arrow to bar' },
            { glyph: '➜', name: 'heavy round-tipped rightwards arrow' },
            { glyph: '➔', name: 'heavy wide-headed rightwards arrow' },
            { glyph: '➤', name: 'black rightwards arrowhead' },
            { glyph: '➝', name: 'triangle-headed rightwards arrow' },
            { glyph: '➞', name: 'heavy triangle-headed rightwards arrow' },
            { glyph: '➟', name: 'dashed triangle-headed rightwards arrow' },
            { glyph: '➠', name: 'heavy dashed triangle-headed rightwards arrow' },
            { glyph: '➡', name: 'black rightwards arrow' },
            { glyph: '▶', name: 'black right-pointing triangle' },
            { glyph: '◀', name: 'black left-pointing triangle' },
            { glyph: '▸', name: 'black right-pointing small triangle' },
            { glyph: '◂', name: 'black left-pointing small triangle' },
            { glyph: '▹', name: 'white right-pointing small triangle' },
            { glyph: '◃', name: 'white left-pointing small triangle' },
            { glyph: '»', name: 'right-pointing double angle quotation mark' },
            { glyph: '«', name: 'left-pointing double angle quotation mark' },
            { glyph: '›', name: 'single right-pointing angle quotation mark' },
            { glyph: '‹', name: 'single left-pointing angle quotation mark' }
        ]
    },
    {
        name: 'Shapes & bullets',
        needsNerdFont: false,
        glyphs: [
            { glyph: '●', name: 'black circle' },
            { glyph: '○', name: 'white circle' },
            { glyph: '◉', name: 'fisheye' },
            { glyph: '◎', name: 'bullseye' },
            { glyph: '◌', name: 'dotted circle' },
            { glyph: '◍', name: 'circle with vertical fill' },
            { glyph: '◐', name: 'circle with left half black' },
            { glyph: '◑', name: 'circle with right half black' },
            { glyph: '◒', name: 'circle with lower half black' },
            { glyph: '◓', name: 'circle with upper half black' },
            { glyph: '•', name: 'bullet' },
            { glyph: '∙', name: 'bullet operator' },
            { glyph: '·', name: 'middle dot' },
            { glyph: '‣', name: 'triangular bullet' },
            { glyph: '⁃', name: 'hyphen bullet' },
            { glyph: '◆', name: 'black diamond' },
            { glyph: '◇', name: 'white diamond' },
            { glyph: '◈', name: 'white diamond containing black small diamond' },
            { glyph: '■', name: 'black square' },
            { glyph: '□', name: 'white square' },
            { glyph: '▪', name: 'black small square' },
            { glyph: '▫', name: 'white small square' },
            { glyph: '▲', name: 'black up-pointing triangle' },
            { glyph: '△', name: 'white up-pointing triangle' },
            { glyph: '▼', name: 'black down-pointing triangle' },
            { glyph: '▽', name: 'white down-pointing triangle' },
            { glyph: '◢', name: 'black lower right triangle' },
            { glyph: '◣', name: 'black lower left triangle' },
            { glyph: '◤', name: 'black upper left triangle' },
            { glyph: '◥', name: 'black upper right triangle' },
            { glyph: '★', name: 'black star' },
            { glyph: '☆', name: 'white star' },
            { glyph: '✦', name: 'black four pointed star' },
            { glyph: '✧', name: 'white four pointed star' },
            { glyph: '✶', name: 'six pointed black star' },
            { glyph: '✷', name: 'eight pointed rectilinear black star' },
            { glyph: '✸', name: 'heavy eight pointed rectilinear black star' },
            { glyph: '✹', name: 'twelve pointed black star' },
            { glyph: '✺', name: 'sixteen pointed asterisk' },
            { glyph: '❖', name: 'black diamond minus white x' },
            { glyph: '❍', name: 'shadowed white circle' },
            { glyph: '⬢', name: 'black hexagon' },
            { glyph: '⬡', name: 'white hexagon' },
            { glyph: '⬤', name: 'black large circle' },
            { glyph: '◯', name: 'large circle' },
            { glyph: '▌', name: 'left half block' },
            { glyph: '▐', name: 'right half block' },
            { glyph: '░', name: 'light shade' },
            { glyph: '▒', name: 'medium shade' },
            { glyph: '▓', name: 'dark shade' }
        ]
    },
    {
        name: 'Text symbols',
        needsNerdFont: false,
        glyphs: [
            { glyph: '✓', name: 'check mark' },
            { glyph: '✔', name: 'heavy check mark' },
            { glyph: '✗', name: 'ballot x' },
            { glyph: '✘', name: 'heavy ballot x' },
            { glyph: '✕', name: 'multiplication x' },
            { glyph: '✖', name: 'heavy multiplication x' },
            { glyph: '✚', name: 'heavy greek cross' },
            { glyph: '✛', name: 'open centre cross' },
            { glyph: '✜', name: 'heavy open centre cross' },
            { glyph: '±', name: 'plus-minus sign' },
            { glyph: '×', name: 'multiplication sign' },
            { glyph: '÷', name: 'division sign' },
            { glyph: '∞', name: 'infinity' },
            { glyph: '≈', name: 'almost equal to' },
            { glyph: '≠', name: 'not equal to' },
            { glyph: '≡', name: 'identical to' },
            { glyph: '≤', name: 'less-than or equal to' },
            { glyph: '≥', name: 'greater-than or equal to' },
            { glyph: 'λ', name: 'greek small letter lamda' },
            { glyph: 'µ', name: 'micro sign' },
            { glyph: 'π', name: 'greek small letter pi' },
            { glyph: 'Σ', name: 'greek capital letter sigma' },
            { glyph: 'Δ', name: 'greek capital letter delta' },
            { glyph: 'Ω', name: 'greek capital letter omega' },
            { glyph: '∂', name: 'partial differential' },
            { glyph: '∑', name: 'n-ary summation' },
            { glyph: '√', name: 'square root' },
            { glyph: '∫', name: 'integral' },
            { glyph: '§', name: 'section sign' },
            { glyph: '¶', name: 'pilcrow sign' },
            { glyph: '†', name: 'dagger' },
            { glyph: '‡', name: 'double dagger' },
            { glyph: '※', name: 'reference mark' },
            { glyph: '⌘', name: 'place of interest sign' },
            { glyph: '⌥', name: 'option key' },
            { glyph: '⇧', name: 'upwards white arrow' },
            { glyph: '⌃', name: 'up arrowhead' },
            { glyph: '⏎', name: 'return symbol' },
            { glyph: '⎇', name: 'alternative key symbol' },
            { glyph: '⌂', name: 'house' },
            { glyph: '✎', name: 'lower right pencil' },
            { glyph: '✐', name: 'upper right pencil' },
            { glyph: '✱', name: 'heavy asterisk' },
            { glyph: '✲', name: 'open centre asterisk' },
            { glyph: '✳', name: 'eight spoked asterisk' },
            { glyph: '⚑', name: 'black flag' },
            { glyph: '⚐', name: 'white flag' },
            { glyph: '♪', name: 'eighth note' },
            { glyph: '♫', name: 'beamed eighth notes' },
            { glyph: '☾', name: 'last quarter moon' },
            { glyph: '☽', name: 'first quarter moon' }
        ]
    },
    {
        name: 'Nerd Font: folders & files',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uF07B', name: 'folder (nf-fa-folder)' },
            { glyph: '\uF07C', name: 'folder open (nf-fa-folder_open)' },
            { glyph: '\uF114', name: 'folder o (nf-fa-folder_o)' },
            { glyph: '\uF115', name: 'folder open o (nf-fa-folder_open_o)' },
            { glyph: '\uE5FF', name: 'folder (nf-custom-folder)' },
            { glyph: '\uE5FE', name: 'folder open (nf-custom-folder_open)' },
            { glyph: '\u{F024B}', name: 'folder (nf-md-folder)' },
            { glyph: '\u{F0770}', name: 'folder open (nf-md-folder_open)' },
            { glyph: '\u{F10B5}', name: 'folder home (nf-md-folder_home)' },
            { glyph: '\u{F107F}', name: 'folder cog (nf-md-folder_cog)' },
            { glyph: '\u{F069D}', name: 'folder star (nf-md-folder_star)' },
            { glyph: '\u{F0250}', name: 'folder lock (nf-md-folder_lock)' },
            { glyph: '\uF413', name: 'file directory (nf-oct-file_directory)' },
            { glyph: '\uF015', name: 'home (nf-fa-home)' },
            { glyph: '\u{F02DC}', name: 'home (nf-md-home)' },
            { glyph: '\uF46D', name: 'home (nf-oct-home)' },
            { glyph: '\uF15B', name: 'file (nf-fa-file)' },
            { glyph: '\uF016', name: 'file o (nf-fa-file_o)' },
            { glyph: '\uF15C', name: 'file text (nf-fa-file_text)' },
            { glyph: '\uF1C9', name: 'file code o (nf-fa-file_code_o)' },
            { glyph: '\uF4A5', name: 'file (nf-oct-file)' },
            { glyph: '\uF40D', name: 'file code (nf-oct-file_code)' },
            { glyph: '\u{F0219}', name: 'file document (nf-md-file_document)' },
            { glyph: '\u{F022E}', name: 'file code (nf-md-file_code)' },
            { glyph: '\uF187', name: 'archive (nf-fa-archive)' },
            { glyph: '\u{F03D6}', name: 'package variant (nf-md-package_variant)' },
            { glyph: '\uF0A0', name: 'hdd o (nf-fa-hdd_o)' },
            { glyph: '\u{F02CA}', name: 'harddisk (nf-md-harddisk)' },
            { glyph: '\uF0C7', name: 'save (nf-fa-save)' },
            { glyph: '\u{F0193}', name: 'content save (nf-md-content_save)' },
            { glyph: '\uF1F8', name: 'trash (nf-fa-trash)' },
            { glyph: '\uF48E', name: 'trash (nf-oct-trash)' },
            { glyph: '\uF0C6', name: 'paperclip (nf-fa-paperclip)' },
            { glyph: '\uF02E', name: 'bookmark (nf-fa-bookmark)' },
            { glyph: '\uF02B', name: 'tag (nf-fa-tag)' },
            { glyph: '\uF02C', name: 'tags (nf-fa-tags)' },
            { glyph: '\uF1C0', name: 'database (nf-fa-database)' },
            { glyph: '\u{F01BC}', name: 'database (nf-md-database)' },
            { glyph: '\uF401', name: 'repo (nf-oct-repo)' },
            { glyph: '\uF405', name: 'book (nf-oct-book)' },
            { glyph: '\uF02D', name: 'book (nf-fa-book)' },
            { glyph: '\u{F0167}', name: 'cloud upload (nf-md-cloud_upload)' },
            { glyph: '\u{F0162}', name: 'cloud download (nf-md-cloud_download)' }
        ]
    },
    {
        name: 'Nerd Font: git',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uE0A0', name: 'branch (nf-pl-branch)' },
            { glyph: '\uF418', name: 'git branch (nf-oct-git_branch)' },
            { glyph: '\uF417', name: 'git commit (nf-oct-git_commit)' },
            { glyph: '\uF419', name: 'git merge (nf-oct-git_merge)' },
            { glyph: '\uF407', name: 'git pull request (nf-oct-git_pull_request)' },
            { glyph: '\uF47F', name: 'git compare (nf-oct-git_compare)' },
            { glyph: '\uE702', name: 'git (nf-dev-git)' },
            { glyph: '\uE725', name: 'git branch (nf-dev-git_branch)' },
            { glyph: '\uE727', name: 'git merge (nf-dev-git_merge)' },
            { glyph: '\uE729', name: 'git commit (nf-dev-git_commit)' },
            { glyph: '\uE726', name: 'git pull request (nf-dev-git_pull_request)' },
            { glyph: '\uE728', name: 'git compare (nf-dev-git_compare)' },
            { glyph: '\uF1D3', name: 'git (nf-fa-git)' },
            { glyph: '\uF09B', name: 'github (nf-fa-github)' },
            { glyph: '\uF113', name: 'github alt (nf-fa-github_alt)' },
            { glyph: '\uF296', name: 'gitlab (nf-fa-gitlab)' },
            { glyph: '\uF126', name: 'code fork (nf-fa-code_fork)' },
            { glyph: '\u{F062C}', name: 'source branch (nf-md-source_branch)' },
            { glyph: '\u{F062D}', name: 'source merge (nf-md-source_merge)' },
            { glyph: '\u{F0718}', name: 'source commit (nf-md-source_commit)' },
            { glyph: '\u{F04C2}', name: 'source pull (nf-md-source_pull)' },
            { glyph: '\u{F04C1}', name: 'source fork (nf-md-source_fork)' },
            { glyph: '\u{F02A4}', name: 'github (nf-md-github)' },
            { glyph: '\u{F0BA0}', name: 'gitlab (nf-md-gitlab)' },
            { glyph: '\u{F02A2}', name: 'git (nf-md-git)' },
            { glyph: '\uF402', name: 'repo forked (nf-oct-repo_forked)' },
            { glyph: '\uF440', name: 'diff (nf-oct-diff)' },
            { glyph: '\uF412', name: 'tag (nf-oct-tag)' },
            { glyph: '\uF51E', name: 'stack (nf-oct-stack)' },
            { glyph: '\uEA68', name: 'source control (nf-cod-source_control)' },
            { glyph: '\uEAFE', name: 'git merge (nf-cod-git_merge)' },
            { glyph: '\uEA64', name: 'git pull request (nf-cod-git_pull_request)' },
            { glyph: '\uF330', name: 'codeberg (nf-linux-codeberg)' },
            { glyph: '\uF335', name: 'forgejo (nf-linux-forgejo)' },
            { glyph: '\u{F00A8}', name: 'bitbucket (nf-md-bitbucket)' },
            { glyph: '\uF408', name: 'mark github (nf-oct-mark_github)' },
            { glyph: '\uF49E', name: 'check circle (nf-oct-check_circle)' },
            { glyph: '\uF52F', name: 'x circle (nf-oct-x_circle)' },
            { glyph: '\uF444', name: 'dot fill (nf-oct-dot_fill)' }
        ]
    },
    {
        name: 'Nerd Font: languages & tools',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uE718', name: 'nodejs small (nf-dev-nodejs_small)' },
            { glyph: '\uE781', name: 'javascript (nf-dev-javascript)' },
            { glyph: '\uE628', name: 'typescript (nf-seti-typescript)' },
            { glyph: '\uE73C', name: 'python (nf-dev-python)' },
            { glyph: '\uE7A8', name: 'rust (nf-dev-rust)' },
            { glyph: '\uE724', name: 'go (nf-dev-go)' },
            { glyph: '\uE739', name: 'ruby (nf-dev-ruby)' },
            { glyph: '\uE73D', name: 'php (nf-dev-php)' },
            { glyph: '\uE738', name: 'java (nf-dev-java)' },
            { glyph: '\uE755', name: 'swift (nf-dev-swift)' },
            { glyph: '\uE777', name: 'haskell (nf-dev-haskell)' },
            { glyph: '\uE737', name: 'scala (nf-dev-scala)' },
            { glyph: '\uE768', name: 'clojure (nf-dev-clojure)' },
            { glyph: '\uE7B1', name: 'erlang (nf-dev-erlang)' },
            { glyph: '\u{F0671}', name: 'language c (nf-md-language_c)' },
            { glyph: '\u{F0672}', name: 'language cpp (nf-md-language_cpp)' },
            { glyph: '\u{F031B}', name: 'language csharp (nf-md-language_csharp)' },
            { glyph: '\u{F1219}', name: 'language kotlin (nf-md-language_kotlin)' },
            { glyph: '\u{F08B1}', name: 'language lua (nf-md-language_lua)' },
            { glyph: '\u{F07D4}', name: 'language r (nf-md-language_r)' },
            { glyph: '\u{F06E6}', name: 'language typescript (nf-md-language_typescript)' },
            { glyph: '\u{F031E}', name: 'language javascript (nf-md-language_javascript)' },
            { glyph: '\u{F0320}', name: 'language python (nf-md-language_python)' },
            { glyph: '\u{F1617}', name: 'language rust (nf-md-language_rust)' },
            { glyph: '\u{F07D3}', name: 'language go (nf-md-language_go)' },
            { glyph: '\uE795', name: 'terminal (nf-dev-terminal)' },
            { glyph: '\uF120', name: 'terminal (nf-fa-terminal)' },
            { glyph: '\uF489', name: 'terminal (nf-oct-terminal)' },
            { glyph: '\uE7B0', name: 'docker (nf-dev-docker)' },
            { glyph: '\u{F10FE}', name: 'kubernetes (nf-md-kubernetes)' },
            { glyph: '\uE7BA', name: 'react (nf-dev-react)' },
            { glyph: '\uE7C5', name: 'vim (nf-dev-vim)' },
            { glyph: '\uE71E', name: 'npm (nf-dev-npm)' },
            { glyph: '\uE62B', name: 'vim (nf-custom-vim)' },
            { glyph: '\uE62D', name: 'elixir (nf-custom-elixir)' },
            { glyph: '\uE60B', name: 'json (nf-seti-json)' },
            { glyph: '\uE73E', name: 'markdown (nf-dev-markdown)' },
            { glyph: '\uE736', name: 'html5 (nf-dev-html5)' },
            { glyph: '\uE749', name: 'css3 (nf-dev-css3)' },
            { glyph: '\u{F1183}', name: 'bash (nf-md-bash)' },
            { glyph: '\u{F1105}', name: 'nix (nf-md-nix)' },
            { glyph: '\u{F06E5}', name: 'language swift (nf-md-language_swift)' },
            { glyph: '\u{F0169}', name: 'code braces (nf-md-code_braces)' },
            { glyph: '\uF121', name: 'code (nf-fa-code)' },
            { glyph: '\u{F0871}', name: 'function variant (nf-md-function_variant)' }
        ]
    },
    {
        name: 'Nerd Font: OS & apps',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uF179', name: 'apple (nf-fa-apple)' },
            { glyph: '\uF17C', name: 'linux (nf-fa-linux)' },
            { glyph: '\uF17A', name: 'windows (nf-fa-windows)' },
            { glyph: '\uF303', name: 'archlinux (nf-linux-archlinux)' },
            { glyph: '\uF306', name: 'debian (nf-linux-debian)' },
            { glyph: '\uF31B', name: 'ubuntu (nf-linux-ubuntu)' },
            { glyph: '\uF30A', name: 'fedora (nf-linux-fedora)' },
            { glyph: '\uF313', name: 'nixos (nf-linux-nixos)' },
            { glyph: '\uF300', name: 'alpine (nf-linux-alpine)' },
            { glyph: '\uF304', name: 'centos (nf-linux-centos)' },
            { glyph: '\uF30C', name: 'freebsd (nf-linux-freebsd)' },
            { glyph: '\uF30D', name: 'gentoo (nf-linux-gentoo)' },
            { glyph: '\uF312', name: 'manjaro (nf-linux-manjaro)' },
            { glyph: '\uF316', name: 'redhat (nf-linux-redhat)' },
            { glyph: '\uF315', name: 'raspberry pi (nf-linux-raspberry_pi)' },
            { glyph: '\uF31A', name: 'tux (nf-linux-tux)' },
            { glyph: '\uF17B', name: 'android (nf-fa-android)' },
            { glyph: '\u{F05B3}', name: 'microsoft windows (nf-md-microsoft_windows)' },
            { glyph: '\u{F0A1E}', name: 'microsoft visual studio code (nf-md-microsoft_visual_studio_code)' },
            { glyph: '\uF268', name: 'chrome (nf-fa-chrome)' },
            { glyph: '\uF269', name: 'firefox (nf-fa-firefox)' },
            { glyph: '\u{F0868}', name: 'docker (nf-md-docker)' },
            { glyph: '\u{F0E0F}', name: 'aws (nf-md-aws)' },
            { glyph: '\u{F11F6}', name: 'google cloud (nf-md-google_cloud)' },
            { glyph: '\u{F0805}', name: 'microsoft azure (nf-md-microsoft_azure)' },
            { glyph: '\uF198', name: 'slack (nf-fa-slack)' },
            { glyph: '\u{F04C7}', name: 'spotify (nf-md-spotify)' },
            { glyph: '\u{F06A9}', name: 'robot (nf-md-robot)' },
            { glyph: '\u{F167A}', name: 'robot outline (nf-md-robot_outline)' },
            { glyph: '\u{F09D1}', name: 'brain (nf-md-brain)' },
            { glyph: '\uF36F', name: 'neovim (nf-linux-neovim)' },
            { glyph: '\u{F0036}', name: 'apple finder (nf-md-apple_finder)' },
            { glyph: '\uF0F4', name: 'coffee (nf-fa-coffee)' }
        ]
    },
    {
        name: 'Nerd Font: status & UI',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uF00C', name: 'check (nf-fa-check)' },
            { glyph: '\uF00D', name: 'times (nf-fa-times)' },
            { glyph: '\uF071', name: 'warning (nf-fa-warning)' },
            { glyph: '\uF05A', name: 'info circle (nf-fa-info_circle)' },
            { glyph: '\uF059', name: 'question circle (nf-fa-question_circle)' },
            { glyph: '\uF06A', name: 'exclamation circle (nf-fa-exclamation_circle)' },
            { glyph: '\uF0E7', name: 'bolt (nf-fa-bolt)' },
            { glyph: '\uF023', name: 'lock (nf-fa-lock)' },
            { glyph: '\uF09C', name: 'unlock (nf-fa-unlock)' },
            { glyph: '\uF084', name: 'key (nf-fa-key)' },
            { glyph: '\uF132', name: 'shield (nf-fa-shield)' },
            { glyph: '\uF017', name: 'clock o (nf-fa-clock_o)' },
            { glyph: '\uF254', name: 'hourglass (nf-fa-hourglass)' },
            { glyph: '\uF073', name: 'calendar (nf-fa-calendar)' },
            { glyph: '\uF013', name: 'cog (nf-fa-cog)' },
            { glyph: '\uF085', name: 'cogs (nf-fa-cogs)' },
            { glyph: '\uF0AD', name: 'wrench (nf-fa-wrench)' },
            { glyph: '\uF188', name: 'bug (nf-fa-bug)' },
            { glyph: '\uF135', name: 'rocket (nf-fa-rocket)' },
            { glyph: '\uF06D', name: 'fire (nf-fa-fire)' },
            { glyph: '\uF004', name: 'heart (nf-fa-heart)' },
            { glyph: '\uF005', name: 'star (nf-fa-star)' },
            { glyph: '\uF0F3', name: 'bell (nf-fa-bell)' },
            { glyph: '\uF1F6', name: 'bell slash (nf-fa-bell_slash)' },
            { glyph: '\uF0C2', name: 'cloud (nf-fa-cloud)' },
            { glyph: '\uF233', name: 'server (nf-fa-server)' },
            { glyph: '\uF108', name: 'desktop (nf-fa-desktop)' },
            { glyph: '\uF109', name: 'laptop (nf-fa-laptop)' },
            { glyph: '\uF2DB', name: 'microchip (nf-fa-microchip)' },
            { glyph: '\uF240', name: 'battery full (nf-fa-battery_full)' },
            { glyph: '\uF012', name: 'signal (nf-fa-signal)' },
            { glyph: '\uF1EB', name: 'wifi (nf-fa-wifi)' },
            { glyph: '\uF1E6', name: 'plug (nf-fa-plug)' },
            { glyph: '\uF155', name: 'dollar (nf-fa-dollar)' },
            { glyph: '\uF0E4', name: 'tachometer (nf-fa-tachometer)' },
            { glyph: '\uF201', name: 'line chart (nf-fa-line_chart)' },
            { glyph: '\uF080', name: 'bar chart (nf-fa-bar_chart)' },
            { glyph: '\uF111', name: 'circle (nf-fa-circle)' },
            { glyph: '\uF10C', name: 'circle o (nf-fa-circle_o)' },
            { glyph: '\uF192', name: 'dot circle o (nf-fa-dot_circle_o)' },
            { glyph: '\uF04B', name: 'play (nf-fa-play)' },
            { glyph: '\uF04C', name: 'pause (nf-fa-pause)' },
            { glyph: '\uF04D', name: 'stop (nf-fa-stop)' },
            { glyph: '\uF021', name: 'refresh (nf-fa-refresh)' },
            { glyph: '\u{F140B}', name: 'lightning bolt (nf-md-lightning_bolt)' },
            { glyph: '\u{F051F}', name: 'timer sand (nf-md-timer_sand)' },
            { glyph: '\u{F029A}', name: 'gauge (nf-md-gauge)' }
        ]
    },
    {
        name: 'Nerd Font: weather',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uE30D', name: 'day sunny (nf-weather-day_sunny)' },
            { glyph: '\uE32B', name: 'night clear (nf-weather-night_clear)' },
            { glyph: '\uE312', name: 'cloudy (nf-weather-cloudy)' },
            { glyph: '\uE302', name: 'day cloudy (nf-weather-day_cloudy)' },
            { glyph: '\uE37E', name: 'night alt cloudy (nf-weather-night_alt_cloudy)' },
            { glyph: '\uE318', name: 'rain (nf-weather-rain)' },
            { glyph: '\uE319', name: 'showers (nf-weather-showers)' },
            { glyph: '\uE31A', name: 'snow (nf-weather-snow)' },
            { glyph: '\uE31D', name: 'thunderstorm (nf-weather-thunderstorm)' },
            { glyph: '\uE313', name: 'fog (nf-weather-fog)' },
            { glyph: '\uE34B', name: 'strong wind (nf-weather-strong_wind)' },
            { glyph: '\uE36B', name: 'hot (nf-weather-hot)' },
            { glyph: '\uE36F', name: 'snowflake cold (nf-weather-snowflake_cold)' },
            { glyph: '\uE350', name: 'thermometer (nf-weather-thermometer)' },
            { glyph: '\uE37C', name: 'umbrella (nf-weather-umbrella)' },
            { glyph: '\uE34C', name: 'sunrise (nf-weather-sunrise)' },
            { glyph: '\uE34D', name: 'sunset (nf-weather-sunset)' },
            { glyph: '\uE39B', name: 'moon full (nf-weather-moon_full)' },
            { glyph: '\uE38D', name: 'moon new (nf-weather-moon_new)' },
            { glyph: '\uE394', name: 'moon first quarter (nf-weather-moon_first_quarter)' },
            { glyph: '\uE3A2', name: 'moon third quarter (nf-weather-moon_third_quarter)' },
            { glyph: '\uE370', name: 'stars (nf-weather-stars)' },
            { glyph: '\uE315', name: 'lightning (nf-weather-lightning)' },
            { glyph: '\uE351', name: 'tornado (nf-weather-tornado)' },
            { glyph: '\uE36C', name: 'hurricane (nf-weather-hurricane)' },
            { glyph: '\uE3BE', name: 'earthquake (nf-weather-earthquake)' },
            { glyph: '\uE3BF', name: 'fire (nf-weather-fire)' },
            { glyph: '\uE371', name: 'raindrop (nf-weather-raindrop)' },
            { glyph: '\uE384', name: 'time 3 (nf-weather-time_3)' },
            { glyph: '\uE387', name: 'time 6 (nf-weather-time_6)' },
            { glyph: '\uE38A', name: 'time 9 (nf-weather-time_9)' },
            { glyph: '\uE381', name: 'time 12 (nf-weather-time_12)' }
        ]
    },
    {
        name: 'Powerline',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uE0A0', name: 'branch (nf-pl-branch)' },
            { glyph: '\uE0A1', name: 'line number (nf-pl-line_number)' },
            { glyph: '\uE0A2', name: 'hostname (nf-pl-hostname)' },
            { glyph: '\uE0A3', name: 'column number (nf-ple-column_number)' },
            { glyph: '\uE0B0', name: 'left hard divider (nf-pl-left_hard_divider)' },
            { glyph: '\uE0B2', name: 'right hard divider (nf-pl-right_hard_divider)' },
            { glyph: '\uE0B1', name: 'left soft divider (nf-pl-left_soft_divider)' },
            { glyph: '\uE0B3', name: 'right soft divider (nf-pl-right_soft_divider)' },
            { glyph: '\uE0B6', name: 'left half circle thick (nf-ple-left_half_circle_thick)' },
            { glyph: '\uE0B4', name: 'right half circle thick (nf-ple-right_half_circle_thick)' },
            { glyph: '\uE0B7', name: 'left half circle thin (nf-ple-left_half_circle_thin)' },
            { glyph: '\uE0B5', name: 'right half circle thin (nf-ple-right_half_circle_thin)' },
            { glyph: '\uE0C0', name: 'flame thick (nf-ple-flame_thick)' },
            { glyph: '\uE0C2', name: 'flame thick mirrored (nf-ple-flame_thick_mirrored)' },
            { glyph: '\uE0C1', name: 'flame thin (nf-ple-flame_thin)' },
            { glyph: '\uE0C3', name: 'flame thin mirrored (nf-ple-flame_thin_mirrored)' },
            { glyph: '\uE0C4', name: 'pixelated squares small (nf-ple-pixelated_squares_small)' },
            { glyph: '\uE0C5', name: 'pixelated squares small mirrored (nf-ple-pixelated_squares_small_mirrored)' },
            { glyph: '\uE0C6', name: 'pixelated squares big (nf-ple-pixelated_squares_big)' },
            { glyph: '\uE0C7', name: 'pixelated squares big mirrored (nf-ple-pixelated_squares_big_mirrored)' },
            { glyph: '\uE0C8', name: 'ice waveform (nf-ple-ice_waveform)' },
            { glyph: '\uE0CA', name: 'ice waveform mirrored (nf-ple-ice_waveform_mirrored)' },
            { glyph: '\uE0CC', name: 'honeycomb (nf-ple-honeycomb)' },
            { glyph: '\uE0CD', name: 'honeycomb outline (nf-ple-honeycomb_outline)' },
            { glyph: '\uE0CE', name: 'lego separator (nf-ple-lego_separator)' },
            { glyph: '\uE0CF', name: 'lego separator thin (nf-ple-lego_separator_thin)' },
            { glyph: '\uE0D0', name: 'lego block facing (nf-ple-lego_block_facing)' },
            { glyph: '\uE0D1', name: 'lego block sideways (nf-ple-lego_block_sideways)' },
            { glyph: '\uE0D2', name: 'trapezoid top bottom (nf-ple-trapezoid_top_bottom)' },
            { glyph: '\uE0D4', name: 'trapezoid top bottom mirrored (nf-ple-trapezoid_top_bottom_mirrored)' },
            { glyph: '\uE0B8', name: 'lower left triangle (nf-ple-lower_left_triangle)' },
            { glyph: '\uE0BA', name: 'lower right triangle (nf-ple-lower_right_triangle)' },
            { glyph: '\uE0BC', name: 'upper left triangle (nf-ple-upper_left_triangle)' },
            { glyph: '\uE0BE', name: 'upper right triangle (nf-ple-upper_right_triangle)' },
            { glyph: '\uE0B9', name: 'backslash separator (nf-ple-backslash_separator)' },
            { glyph: '\uE0BB', name: 'forwardslash separator (nf-ple-forwardslash_separator)' }
        ]
    }
];
