// The glyphs the glyph editor's picker offers to browse: the commonly useful
// ones, with emoji in Unicode's categories, then one-cell Unicode symbols, then
// Nerd Font icons. Searching finds these and every other emoji, symbol and Nerd
// Font icon. Each group draws its glyphs at one width, so its grid lines up.
// Names come from Unicode and, for Nerd Font icons, from the Nerd Fonts glyph
// names (nf-...). The Nerd Font group draws as boxes without a Nerd Font.
export interface GlyphEntry {
    glyph: string;
    name: string;
    /** An emoji that takes a skin tone: its light tone version, which the other tones are made from. */
    lightTone?: string;
}

export interface GlyphGroup {
    name: string;
    needsNerdFont: boolean;
    glyphs: GlyphEntry[];
}

export const GLYPH_GROUPS: GlyphGroup[] = [
    {
        name: 'Smileys & Emotion',
        needsNerdFont: false,
        glyphs: [
            { glyph: '😀', name: 'grinning face' },
            { glyph: '😃', name: 'grinning face with big eyes' },
            { glyph: '😄', name: 'grinning face with smiling eyes' },
            { glyph: '😁', name: 'beaming face with smiling eyes' },
            { glyph: '😆', name: 'grinning squinting face' },
            { glyph: '😅', name: 'grinning face with sweat' },
            { glyph: '🙂', name: 'slightly smiling face' },
            { glyph: '🙃', name: 'upside-down face' },
            { glyph: '🫠', name: 'melting face' },
            { glyph: '😊', name: 'smiling face with smiling eyes' },
            { glyph: '😇', name: 'smiling face with halo' },
            { glyph: '🥰', name: 'smiling face with hearts' },
            { glyph: '😍', name: 'smiling face with heart-eyes' },
            { glyph: '🤩', name: 'star-struck' },
            { glyph: '☺️', name: 'smiling face' },
            { glyph: '🥲', name: 'smiling face with tear' },
            { glyph: '😋', name: 'face savoring food' },
            { glyph: '😛', name: 'face with tongue' },
            { glyph: '😜', name: 'winking face with tongue' },
            { glyph: '🤪', name: 'zany face' },
            { glyph: '😝', name: 'squinting face with tongue' },
            { glyph: '🤑', name: 'money-mouth face' },
            { glyph: '🤗', name: 'smiling face with open hands' },
            { glyph: '🤭', name: 'face with hand over mouth' },
            { glyph: '🫢', name: 'face with open eyes and hand over mouth' },
            { glyph: '🫣', name: 'face with peeking eye' },
            { glyph: '🤔', name: 'thinking face' },
            { glyph: '🫡', name: 'saluting face' },
            { glyph: '🤨', name: 'face with raised eyebrow' },
            { glyph: '😐', name: 'neutral face' },
            { glyph: '😑', name: 'expressionless face' },
            { glyph: '🫥', name: 'dotted line face' },
            { glyph: '😏', name: 'smirking face' },
            { glyph: '😒', name: 'unamused face' },
            { glyph: '🙄', name: 'face with rolling eyes' },
            { glyph: '😬', name: 'grimacing face' },
            { glyph: '😮‍💨', name: 'face exhaling' },
            { glyph: '🫨', name: 'shaking face' },
            { glyph: '😔', name: 'pensive face' },
            { glyph: '😴', name: 'sleeping face' },
            { glyph: '🫩', name: 'face with bags under eyes' },
            { glyph: '🤒', name: 'face with thermometer' },
            { glyph: '🤕', name: 'face with head-bandage' },
            { glyph: '🤢', name: 'nauseated face' },
            { glyph: '🤮', name: 'face vomiting' },
            { glyph: '🥵', name: 'hot face' },
            { glyph: '🥶', name: 'cold face' },
            { glyph: '😵', name: 'face with crossed-out eyes' },
            { glyph: '😵‍💫', name: 'face with spiral eyes' },
            { glyph: '🤯', name: 'exploding head' },
            { glyph: '🤠', name: 'cowboy hat face' },
            { glyph: '🥳', name: 'partying face' },
            { glyph: '🥸', name: 'disguised face' },
            { glyph: '😎', name: 'smiling face with sunglasses' },
            { glyph: '🤓', name: 'nerd face' },
            { glyph: '🧐', name: 'face with monocle' },
            { glyph: '😕', name: 'confused face' },
            { glyph: '🫤', name: 'face with diagonal mouth' },
            { glyph: '😟', name: 'worried face' },
            { glyph: '🙁', name: 'slightly frowning face' },
            { glyph: '☹️', name: 'frowning face' },
            { glyph: '😮', name: 'face with open mouth' },
            { glyph: '😯', name: 'hushed face' },
            { glyph: '😲', name: 'astonished face' },
            { glyph: '😳', name: 'flushed face' },
            { glyph: '🥺', name: 'pleading face' },
            { glyph: '🥹', name: 'face holding back tears' },
            { glyph: '😧', name: 'anguished face' },
            { glyph: '😨', name: 'fearful face' },
            { glyph: '😰', name: 'anxious face with sweat' },
            { glyph: '😥', name: 'sad but relieved face' },
            { glyph: '😭', name: 'loudly crying face' },
            { glyph: '😱', name: 'face screaming in fear' },
            { glyph: '😖', name: 'confounded face' },
            { glyph: '😣', name: 'persevering face' },
            { glyph: '😞', name: 'disappointed face' },
            { glyph: '🥱', name: 'yawning face' },
            { glyph: '😡', name: 'enraged face' },
            { glyph: '😠', name: 'angry face' },
            { glyph: '🤬', name: 'face with symbols on mouth' },
            { glyph: '😈', name: 'smiling face with horns' },
            { glyph: '👿', name: 'angry face with horns' },
            { glyph: '💀', name: 'skull' },
            { glyph: '☠️', name: 'skull and crossbones' },
            { glyph: '💩', name: 'pile of poo' },
            { glyph: '🤡', name: 'clown face' },
            { glyph: '👻', name: 'ghost' },
            { glyph: '👽', name: 'alien' },
            { glyph: '👾', name: 'alien monster' },
            { glyph: '🤖', name: 'robot' },
            { glyph: '🙈', name: 'see-no-evil monkey' },
            { glyph: '🙉', name: 'hear-no-evil monkey' },
            { glyph: '🙊', name: 'speak-no-evil monkey' },
            { glyph: '💕', name: 'two hearts' },
            { glyph: '💔', name: 'broken heart' },
            { glyph: '❤️‍🔥', name: 'heart on fire' },
            { glyph: '❤️‍🩹', name: 'mending heart' },
            { glyph: '❤️', name: 'red heart' },
            { glyph: '🩷', name: 'pink heart' },
            { glyph: '🧡', name: 'orange heart' },
            { glyph: '💛', name: 'yellow heart' },
            { glyph: '💚', name: 'green heart' },
            { glyph: '💙', name: 'blue heart' },
            { glyph: '🩵', name: 'light blue heart' },
            { glyph: '💜', name: 'purple heart' },
            { glyph: '🤎', name: 'brown heart' },
            { glyph: '🖤', name: 'black heart' },
            { glyph: '🩶', name: 'grey heart' },
            { glyph: '🤍', name: 'white heart' },
            { glyph: '💯', name: 'hundred points' },
            { glyph: '💥', name: 'collision' },
            { glyph: '💦', name: 'sweat droplets' },
            { glyph: '💬', name: 'speech balloon' },
            { glyph: '💭', name: 'thought balloon' },
            { glyph: '💤', name: 'ZZZ' }
        ]
    },
    {
        name: 'People & Body',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🤚', name: 'raised back of hand' },
            { glyph: '✋', name: 'raised hand' },
            { glyph: '👌', name: 'OK hand' },
            { glyph: '👈', name: 'backhand index pointing left' },
            { glyph: '👉', name: 'backhand index pointing right' },
            { glyph: '👆', name: 'backhand index pointing up' },
            { glyph: '🖕', name: 'middle finger' },
            { glyph: '👇', name: 'backhand index pointing down' },
            { glyph: '☝️', name: 'index pointing up' },
            { glyph: '🫵', name: 'index pointing at the viewer' },
            { glyph: '👍', name: 'thumbs up' },
            { glyph: '👎', name: 'thumbs down' },
            { glyph: '🧠', name: 'brain' },
            { glyph: '🦴', name: 'bone' },
            { glyph: '👀', name: 'eyes' }
        ]
    },
    {
        name: 'Animals & Nature',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🐵', name: 'monkey face' },
            { glyph: '🐶', name: 'dog face' },
            { glyph: '🐺', name: 'wolf' },
            { glyph: '🦊', name: 'fox' },
            { glyph: '🐱', name: 'cat face' },
            { glyph: '🦄', name: 'unicorn' },
            { glyph: '🐮', name: 'cow face' },
            { glyph: '🐰', name: 'rabbit face' },
            { glyph: '🦔', name: 'hedgehog' },
            { glyph: '🦥', name: 'sloth' },
            { glyph: '🦦', name: 'otter' },
            { glyph: '🦨', name: 'skunk' },
            { glyph: '🦡', name: 'badger' },
            { glyph: '🐧', name: 'penguin' },
            { glyph: '🐦‍🔥', name: 'phoenix' },
            { glyph: '🐸', name: 'frog' },
            { glyph: '🐢', name: 'turtle' },
            { glyph: '🦖', name: 'T-Rex' },
            { glyph: '🐳', name: 'spouting whale' },
            { glyph: '🐙', name: 'octopus' },
            { glyph: '🌱', name: 'seedling' },
            { glyph: '🌲', name: 'evergreen tree' },
            { glyph: '🌿', name: 'herb' },
            { glyph: '🍀', name: 'four leaf clover' },
            { glyph: '🍄', name: 'mushroom' }
        ]
    },
    {
        name: 'Travel & Places',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🧭', name: 'compass' },
            { glyph: '🚨', name: 'police car light' },
            { glyph: '🛑', name: 'stop sign' },
            { glyph: '🚧', name: 'construction' },
            { glyph: '🚀', name: 'rocket' },
            { glyph: '🛸', name: 'flying saucer' },
            { glyph: '⌛', name: 'hourglass done' },
            { glyph: '⏳', name: 'hourglass not done' },
            { glyph: '⏰', name: 'alarm clock' },
            { glyph: '🌚', name: 'new moon face' },
            { glyph: '⭐', name: 'star' },
            { glyph: '🌈', name: 'rainbow' },
            { glyph: '⚡', name: 'high voltage' },
            { glyph: '❄️', name: 'snowflake' },
            { glyph: '🔥', name: 'fire' },
            { glyph: '💧', name: 'droplet' }
        ]
    },
    {
        name: 'Activities',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🎉', name: 'party popper' },
            { glyph: '🎯', name: 'bullseye' },
            { glyph: '🎱', name: 'pool 8 ball' },
            { glyph: '🔮', name: 'crystal ball' },
            { glyph: '♠️', name: 'spade suit' },
            { glyph: '♥️', name: 'heart suit' },
            { glyph: '♦️', name: 'diamond suit' },
            { glyph: '♣️', name: 'club suit' }
        ]
    },
    {
        name: 'Objects',
        needsNerdFont: false,
        glyphs: [
            { glyph: '💎', name: 'gem stone' },
            { glyph: '🔇', name: 'muted speaker' },
            { glyph: '🔈', name: 'speaker low volume' },
            { glyph: '🔔', name: 'bell' },
            { glyph: '🔕', name: 'bell with slash' },
            { glyph: '🔋', name: 'battery' },
            { glyph: '🪫', name: 'low battery' },
            { glyph: '🔌', name: 'electric plug' },
            { glyph: '💾', name: 'floppy disk' },
            { glyph: '💰', name: 'money bag' },
            { glyph: '💸', name: 'money with wings' },
            { glyph: '📁', name: 'file folder' },
            { glyph: '📂', name: 'open file folder' },
            { glyph: '🔒', name: 'locked' },
            { glyph: '🔓', name: 'unlocked' },
            { glyph: '🔐', name: 'locked with key' },
            { glyph: '🔑', name: 'key' },
            { glyph: '⚰️', name: 'coffin' },
            { glyph: '🪦', name: 'headstone' }
        ]
    },
    {
        name: 'Symbols',
        needsNerdFont: false,
        glyphs: [
            { glyph: '⚠️', name: 'warning' },
            { glyph: '⛔', name: 'no entry' },
            { glyph: '🚫', name: 'prohibited' },
            { glyph: '☢️', name: 'radioactive' },
            { glyph: '☣️', name: 'biohazard' },
            { glyph: '❓', name: 'red question mark' },
            { glyph: '❗', name: 'red exclamation mark' },
            { glyph: '⭕', name: 'hollow red circle' },
            { glyph: '✅', name: 'check mark button' },
            { glyph: '❌', name: 'cross mark' },
            { glyph: '❎', name: 'cross mark button' },
            { glyph: '#️⃣', name: 'keycap: #' },
            { glyph: '*️⃣', name: 'keycap: *' },
            { glyph: '0️⃣', name: 'keycap: 0' },
            { glyph: '1️⃣', name: 'keycap: 1' },
            { glyph: '2️⃣', name: 'keycap: 2' },
            { glyph: '3️⃣', name: 'keycap: 3' },
            { glyph: '4️⃣', name: 'keycap: 4' },
            { glyph: '5️⃣', name: 'keycap: 5' },
            { glyph: '6️⃣', name: 'keycap: 6' },
            { glyph: '7️⃣', name: 'keycap: 7' },
            { glyph: '8️⃣', name: 'keycap: 8' },
            { glyph: '9️⃣', name: 'keycap: 9' },
            { glyph: '🔟', name: 'keycap: 10' },
            { glyph: '🔴', name: 'red circle' },
            { glyph: '🟠', name: 'orange circle' },
            { glyph: '🟡', name: 'yellow circle' },
            { glyph: '🟢', name: 'green circle' },
            { glyph: '🔵', name: 'blue circle' },
            { glyph: '🟣', name: 'purple circle' },
            { glyph: '🟤', name: 'brown circle' },
            { glyph: '⚫', name: 'black circle' },
            { glyph: '⚪', name: 'white circle' },
            { glyph: '🟥', name: 'red square' },
            { glyph: '🟧', name: 'orange square' },
            { glyph: '🟨', name: 'yellow square' },
            { glyph: '🟩', name: 'green square' },
            { glyph: '🟦', name: 'blue square' },
            { glyph: '🟪', name: 'purple square' },
            { glyph: '🟫', name: 'brown square' },
            { glyph: '⬛', name: 'black large square' },
            { glyph: '⬜', name: 'white large square' },
            { glyph: '🔺', name: 'red triangle pointed up' },
            { glyph: '🔻', name: 'red triangle pointed down' }
        ]
    },
    {
        name: 'Flags',
        needsNerdFont: false,
        glyphs: [
            { glyph: '🏁', name: 'chequered flag' },
            { glyph: '🚩', name: 'triangular flag' },
            { glyph: '🏴', name: 'black flag' },
            { glyph: '🏳️', name: 'white flag' },
            { glyph: '🏳️‍🌈', name: 'rainbow flag' },
            { glyph: '🏳️‍⚧️', name: 'transgender flag' },
            { glyph: '🏴‍☠️', name: 'pirate flag' }
        ]
    },
    {
        name: 'Arrows & symbols',
        needsNerdFont: false,
        glyphs: [
            { glyph: '←', name: 'leftwards arrow' },
            { glyph: '↑', name: 'upwards arrow' },
            { glyph: '→', name: 'rightwards arrow' },
            { glyph: '↓', name: 'downwards arrow' },
            { glyph: '↰', name: 'upwards arrow with tip leftwards' },
            { glyph: '↱', name: 'upwards arrow with tip rightwards' },
            { glyph: '↳', name: 'downwards arrow with tip rightwards' },
            { glyph: '↴', name: 'rightwards arrow with corner downwards' },
            { glyph: '↵', name: 'downwards arrow with corner leftwards' },
            { glyph: '↶', name: 'anticlockwise top semicircle arrow' },
            { glyph: '↷', name: 'clockwise top semicircle arrow' },
            { glyph: '↺', name: 'anticlockwise open circle arrow' },
            { glyph: '↻', name: 'clockwise open circle arrow' },
            { glyph: '⇄', name: 'rightwards arrow over leftwards arrow' },
            { glyph: '⇅', name: 'upwards arrow leftwards of downwards arrow' },
            { glyph: '⇆', name: 'leftwards arrow over rightwards arrow' },
            { glyph: '⇠', name: 'leftwards dashed arrow' },
            { glyph: '⇡', name: 'upwards dashed arrow' },
            { glyph: '⇢', name: 'rightwards dashed arrow' },
            { glyph: '⇣', name: 'downwards dashed arrow' },
            { glyph: '⇤', name: 'leftwards arrow to bar' },
            { glyph: '⇥', name: 'rightwards arrow to bar' },
            { glyph: '⟲', name: 'anticlockwise gapped circle arrow' },
            { glyph: '⟳', name: 'clockwise gapped circle arrow' },
            { glyph: '○', name: 'white circle' },
            { glyph: '◌', name: 'dotted circle' },
            { glyph: '◢', name: 'black lower right triangle' },
            { glyph: '◣', name: 'black lower left triangle' },
            { glyph: '◤', name: 'black upper left triangle' },
            { glyph: '◥', name: 'black upper right triangle' },
            { glyph: '☢', name: 'radioactive sign' },
            { glyph: '☣', name: 'biohazard sign' },
            { glyph: '⚠', name: 'warning sign' },
            { glyph: '⚰', name: 'coffin' },
            { glyph: '✓', name: 'check mark' },
            { glyph: '✔', name: 'heavy check mark' },
            { glyph: '✕', name: 'multiplication x' },
            { glyph: '✖', name: 'heavy multiplication x' },
            { glyph: '✗', name: 'ballot x' },
            { glyph: '✘', name: 'heavy ballot x' },
            { glyph: '✚', name: 'heavy greek cross' },
            { glyph: '➔', name: 'heavy wide-headed rightwards arrow' },
            { glyph: '➜', name: 'heavy round-tipped rightwards arrow' },
            { glyph: '➝', name: 'triangle-headed rightwards arrow' },
            { glyph: '➞', name: 'heavy triangle-headed rightwards arrow' },
            { glyph: '➟', name: 'dashed triangle-headed rightwards arrow' },
            { glyph: '➠', name: 'heavy dashed triangle-headed rightwards arrow' },
            { glyph: '➡', name: 'black rightwards arrow' },
            { glyph: '➤', name: 'black rightwards arrowhead' }
        ]
    },
    {
        name: 'Nerd Font',
        needsNerdFont: true,
        glyphs: [
            { glyph: '\uEB99', name: 'account (nf-cod-account)' },
            { glyph: '\uEA99', name: 'arrow both (nf-cod-arrow_both)' },
            { glyph: '\uEBFC', name: 'arrow circle down (nf-cod-arrow_circle_down)' },
            { glyph: '\uEBFD', name: 'arrow circle left (nf-cod-arrow_circle_left)' },
            { glyph: '\uEBFE', name: 'arrow circle right (nf-cod-arrow_circle_right)' },
            { glyph: '\uEBFF', name: 'arrow circle up (nf-cod-arrow_circle_up)' },
            { glyph: '\uEA9A', name: 'arrow down (nf-cod-arrow_down)' },
            { glyph: '\uEA9B', name: 'arrow left (nf-cod-arrow_left)' },
            { glyph: '\uEA9C', name: 'arrow right (nf-cod-arrow_right)' },
            { glyph: '\uEA9D', name: 'arrow small down (nf-cod-arrow_small_down)' },
            { glyph: '\uEA9E', name: 'arrow small left (nf-cod-arrow_small_left)' },
            { glyph: '\uEA9F', name: 'arrow small right (nf-cod-arrow_small_right)' },
            { glyph: '\uEAA0', name: 'arrow small up (nf-cod-arrow_small_up)' },
            { glyph: '\uEBCB', name: 'arrow swap (nf-cod-arrow_swap)' },
            { glyph: '\uEAA1', name: 'arrow up (nf-cod-arrow_up)' },
            { glyph: '\uEBB1', name: 'check all (nf-cod-check_all)' },
            { glyph: '\uEC6F', name: 'git branch (nf-cod-git_branch)' },
            { glyph: '\uEC6C', name: 'git branch changes (nf-cod-git_branch_changes)' },
            { glyph: '\uEC6E', name: 'git branch conflicts (nf-cod-git_branch_conflicts)' },
            { glyph: '\uEC6D', name: 'git branch staged changes (nf-cod-git_branch_staged_changes)' },
            { glyph: '\uEAFD', name: 'git compare (nf-cod-git_compare)' },
            { glyph: '\uEAFE', name: 'git merge (nf-cod-git_merge)' },
            { glyph: '\uEA64', name: 'git pull request (nf-cod-git_pull_request)' },
            { glyph: '\uEBDA', name: 'git pull request closed (nf-cod-git_pull_request_closed)' },
            { glyph: '\uEBBC', name: 'git pull request create (nf-cod-git_pull_request_create)' },
            { glyph: '\uEC46', name: 'git pull request done (nf-cod-git_pull_request_done)' },
            { glyph: '\uEBDB', name: 'git pull request draft (nf-cod-git_pull_request_draft)' },
            { glyph: '\uEA84', name: 'github (nf-cod-github)' },
            { glyph: '\uEB00', name: 'github alt (nf-cod-github_alt)' },
            { glyph: '\uEBA1', name: 'github inverted (nf-cod-github_inverted)' },
            { glyph: '\uEA68', name: 'source control (nf-cod-source_control)' },
            { glyph: '\uE62D', name: 'elixir (nf-custom-elixir, nf-seti-elixir)' },
            { glyph: '\uE5FF', name: 'folder (nf-custom-folder)' },
            { glyph: '\uE5FB', name: 'folder git (nf-custom-folder_git, nf-custom-folder_git_branch)' },
            { glyph: '\uE5FA', name: 'folder npm (nf-custom-folder_npm)' },
            { glyph: '\uE5FE', name: 'folder open (nf-custom-folder_open)' },
            { glyph: '\uE62B', name: 'vim (nf-custom-vim)' },
            { glyph: '\uE702', name: 'git (nf-dev-git)' },
            { glyph: '\uE725', name: 'git branch (nf-dev-git_branch)' },
            { glyph: '\uE728', name: 'git compare (nf-dev-git_compare)' },
            { glyph: '\uE726', name: 'git pull request (nf-dev-git_pull_request)' },
            { glyph: '\uF021', name: 'arrows rotate (nf-fa-arrows_rotate, nf-fa-refresh)' },
            { glyph: '\uF0F3', name: 'bell (nf-fa-bell)' },
            { glyph: '\uF1F6', name: 'bell slash (nf-fa-bell_slash)' },
            { glyph: '\uF0E7', name: 'bolt (nf-fa-bolt, nf-fa-flash)' },
            { glyph: '\uF02E', name: 'bookmark (nf-fa-bookmark)' },
            { glyph: '\uF188', name: 'bug (nf-fa-bug)' },
            { glyph: '\uF00C', name: 'check (nf-fa-check)' },
            { glyph: '\uF017', name: 'clock (nf-fa-clock, nf-fa-clock_o)' },
            { glyph: '\uF00D', name: 'close (nf-fa-close, nf-fa-remove, nf-fa-times, nf-fa-xmark)' },
            { glyph: '\uF0C2', name: 'cloud (nf-fa-cloud)' },
            { glyph: '\uF126', name: 'code branch (nf-fa-code_branch, nf-fa-code_fork)' },
            { glyph: '\uF07B', name: 'folder (nf-fa-folder)' },
            { glyph: '\uF07C', name: 'folder open (nf-fa-folder_open)' },
            { glyph: '\uF09B', name: 'github (nf-fa-github)' },
            { glyph: '\uF023', name: 'lock (nf-fa-lock)' },
            { glyph: '\uF2FC', name: 'lock open (nf-fa-lock_open)' },
            { glyph: '\uF04B', name: 'play (nf-fa-play)' },
            { glyph: '\uF1E6', name: 'plug (nf-fa-plug)' },
            { glyph: '\uEE0D', name: 'robot (nf-fa-robot)' },
            { glyph: '\uF135', name: 'rocket (nf-fa-rocket)' },
            { glyph: '\uEF8D', name: 'sack dollar (nf-fa-sack_dollar)' },
            { glyph: '\uF132', name: 'shield (nf-fa-shield)' },
            { glyph: '\uF02B', name: 'tag (nf-fa-tag)' },
            { glyph: '⏻', name: 'power (nf-iec-power)' },
            { glyph: '\u{F089A}', name: 'alien (nf-md-alien)' },
            { glyph: '\u{F10CB}', name: 'alien outline (nf-md-alien_outline)' },
            { glyph: '\u{F0162}', name: 'cloud download (nf-md-cloud_download)' },
            { glyph: '\u{F0167}', name: 'cloud upload (nf-md-cloud_upload)' },
            { glyph: '\u{F024B}', name: 'folder (nf-md-folder)' },
            { glyph: '\u{F0250}', name: 'folder lock (nf-md-folder_lock)' },
            { glyph: '\u{F0770}', name: 'folder open (nf-md-folder_open)' },
            { glyph: '\u{F02A2}', name: 'git (nf-md-git)' },
            { glyph: '\u{F02A4}', name: 'github (nf-md-github)' },
            { glyph: '\u{F0BA0}', name: 'gitlab (nf-md-gitlab)' },
            { glyph: '\u{F140B}', name: 'lightning bolt (nf-md-lightning_bolt)' },
            { glyph: '\u{F06A9}', name: 'robot (nf-md-robot)' },
            { glyph: '\u{F169D}', name: 'robot angry (nf-md-robot_angry)' },
            { glyph: '\u{F0BC6}', name: 'skull crossbones (nf-md-skull_crossbones)' },
            { glyph: '\u{F062C}', name: 'source branch (nf-md-source_branch)' },
            { glyph: '\u{F04C2}', name: 'source pull (nf-md-source_pull)' },
            { glyph: '\uF418', name: 'git branch (nf-oct-git_branch)' },
            { glyph: '\uF47F', name: 'git compare (nf-oct-git_compare)' },
            { glyph: '\uF407', name: 'git pull request (nf-oct-git_pull_request)' },
            { glyph: '\uF408', name: 'mark github (nf-oct-mark_github)' },
            { glyph: '\uE0A0', name: 'branch (nf-pl-branch)' },
            { glyph: '\uE0B0', name: 'left hard divider (nf-pl-left_hard_divider)' },
            { glyph: '\uE0B1', name: 'left soft divider (nf-pl-left_soft_divider)' },
            { glyph: '\uE0B2', name: 'right hard divider (nf-pl-right_hard_divider)' },
            { glyph: '\uE0B3', name: 'right soft divider (nf-pl-right_soft_divider)' },
            { glyph: '\uE007', name: 'away (nf-pom-away)' },
            { glyph: '\uE36E', name: 'alien (nf-weather-alien)' }
        ]
    }
];
