#!/usr/bin/env bun

// Regenerates src/widgets/shared/nerd-font-glyphs.ts, the glyph picker's full
// Nerd Font set, from Nerd Fonts' glyph names:
//
//   curl -sLO https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json
//   bun scripts/generate-nerd-font-glyphs.ts
//
// It reads glyphnames.json from the current directory (the repo root).
//
// Names that share a codepoint (aliases across icon sets) become one entry.

import {
    existsSync,
    readFileSync,
    writeFileSync
} from 'node:fs';

interface GlyphName {
    char: string;
    code: string;
}

const OUTPUT = 'src/widgets/shared/nerd-font-glyphs.ts';
const SOURCE = 'glyphnames.json';
if (!existsSync(SOURCE)) {
    console.error(`No ${SOURCE} here: download it into the repo root first (see the top of this script).`);
    process.exit(1);
}

const data = JSON.parse(readFileSync(SOURCE, 'utf-8')) as Record<string, GlyphName | { version?: string }>;
const version = (data.METADATA as { version?: string } | undefined)?.version ?? 'unknown';

// Codepoint → its names, in the file's order
const namesByCode = new Map<string, string[]>();
for (const [name, entry] of Object.entries(data)) {
    if (name === 'METADATA' || !('code' in entry)) {
        continue;
    }
    namesByCode.set(entry.code, [...(namesByCode.get(entry.code) ?? []), name]);
}

// One string per icon set (the name's prefix), entries "code name name;..."
const sets = new Map<string, string[]>();
for (const [code, names] of namesByCode) {
    const set = names[0]?.split('-')[0] ?? 'other';
    sets.set(set, [...(sets.get(set) ?? []), `${code} ${names.join(' ')}`]);
}

const lines = [...sets.entries()].map(([set, entries]) => `    { id: '${set}', glyphs: '${entries.join(';')}' }`);
writeFileSync(OUTPUT, `// Generated by scripts/generate-nerd-font-glyphs.ts from Nerd Fonts ${version}
// glyph names. Do not edit by hand; regenerate it instead.
//
// Each icon set (its id is the names' prefix) holds its glyphs as
// "code name name;...": the hex codepoint, then every Nerd Font name for it
// (without the "nf-" prefix).
export const NERD_FONT_VERSION = '${version}';

export const NERD_FONT_SETS: readonly { id: string; glyphs: string }[] = [
${lines.join(',\n')}
];
`);
console.log(`Wrote ${namesByCode.size} glyphs in ${sets.size} sets to ${OUTPUT}`);
